In [ ]:
import pandas as pd
patient=pd.read_csv("Patient_Data.csv")
patient

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [2]:
patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 464.0+ bytes

In [3]:
billing_columns=patient[['PatientID', 'Department', 'Doctor', 'BillAmount']]
billing_columns

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [4]:
patient.drop(columns=['ReceptionistID','CheckInTime'],inplace=True)

In [5]:
patient

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [6]:
department_bill=patient.groupby('Department')['BillAmount'].sum()
department_bill

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [9]:
patient=patient.drop_duplicates(subset='PatientID')
patient

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [11]:
mean_bill=patient['BillAmount'].mean()
patient['BillAmount']=patient['BillAmount'].fillna(mean_bill)
patient

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [ ]:
billing=pd.read_csv("Billing_Data.csv")
billing

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [14]:
merge_data=pd.merge(patient,billing,on='PatientID',how='inner')
merge_data

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [16]:
new_patient=pd.DataFrame({'PatientID':[106,107],'Name':['Jhon','Smith'],'Department':['Cardiology','Neurology'],'Doctor':['Dr.Smith','Dr.Jhon'],'BillAmount':[5000,6000]})

In [17]:
updated_patient=pd.concat([patient,new_patient],axis=0,ignore_index=True)
updated_patient

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
5        106     Jhon   Cardiology   Dr.Smith  5000.000000
6        107    Smith    Neurology    Dr.Jhon  6000.000000

In [18]:
new_billing_columns = pd.DataFrame({
    'InsuranceCovered': [True, False],
    'FinalAmount': [4500, 7000]
})

In [19]:
final_data = pd.concat([updated_patient, new_billing_columns], axis=1)

final_data

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,True,4500.0
1,102,Bob,Neurology,Dr. John,6233.333333,False,7000.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,NaN,NaN
3,104,David,Cardiology,Dr. Smith,6200.000000,NaN,NaN
4,105,Eva,Dermatology,Dr. Rose,6233.333333,NaN,NaN
5,106,Jhon,Cardiology,Dr.Smith,5000.000000,NaN,NaN
6,107,Smith,Neurology,Dr.Jhon,6000.000000,NaN,NaN