### Section A Data Structures & Control Structures

In [1]:
num=[5,2,4,8,9]

print(num)

num.append(10)
print("After Append",num)

num.extend([11,12,13])
print("After Extend",num)

num.insert(2,15)
print("After Insert",num)

num.remove(4)
print("After Remove",num)

removed=num.pop()

print("After Pop",num)
print("Removed Element",removed)

print("Index of 8 is",num.index(8))

print("Count of 9 is",num.count(9))

num.sort()
print("After Sort",num)

num.reverse()
print("After Reverse",num)

[5, 2, 4, 8, 9]
After Append [5, 2, 4, 8, 9, 10]
After Extend [5, 2, 4, 8, 9, 10, 11, 12, 13]
After Insert [5, 2, 15, 4, 8, 9, 10, 11, 12, 13]
After Remove [5, 2, 15, 8, 9, 10, 11, 12, 13]
After Pop [5, 2, 15, 8, 9, 10, 11, 12]
Removed Element 13
Index of 8 is 3
Count of 9 is 1
After Sort [2, 5, 8, 9, 10, 11, 12, 15]
After Reverse [15, 12, 11, 10, 9, 8, 5, 2]

In [2]:
students=("rahul","uday","sachin")
print("Original students",students)

students[1]="vijay" 
print("After Change",students)

Original students ('rahul', 'uday', 'sachin')

TypeError: 'tuple' object does not support item assignment

The second name cannot be changed because tuples are immutable in Python once a tuple is created the elements cannot be modified.

In [3]:
num={2,3,1,5,6,4,3,2}
print(num)

{1, 2, 3, 4, 5, 6}

A set automatically removes duplicate values and stores only unique elements.

In [4]:
student={"Name":"Uday","Age":22,"Course":"Python"}

student["Age"]=23

student["email"]="udaykumar@gmail.com"

print(student)

{'Name': 'Uday', 'Age': 23, 'Course': 'Python', 'email': 'udaykumar@gmail.com'}

In [5]:
age=int(input("Enter your age: "))

print("you are eligable to vote" if age>=18 else "you are not eligable to vote")

you are eligable to vote

In [6]:
marks=int(input("Enter your marks: "))

print("A") if marks >=90 else print("B") if marks >75 and marks <89 else print("C") if marks >50 and marks <74 else print("Fail")

Fail

In [8]:
num=int(input("Enter the number"))
if num==0:
    print("The number is zero")
elif num>0:
    if num%2==0:
        print("The number is positive and even")
    else:
        print("The number is positive and odd")
else:
    print("The number is negative")

The number is positive and odd

### Section B Numpy

In [9]:
import numpy as np

scalar = np.array(5)
print("Scalar:", scalar)


array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)


array_2d = np.array([
    [10, 20, 30],
    [40, 50, 60]])
print("2D Array:")
print(array_2d)

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
[[10 20 30]
 [40 50 60]]

In [10]:
import numpy as np

array=np.random.randint(0,101,size=(4,4))

print(array)

[[ 14  13  97   8]
 [ 60  26  11  57]
 [ 96  59  39  68]
 [ 37  23  21 100]]

In [11]:
import numpy as np
import pandas as pd

array=np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

arr2=pd.DataFrame(array,columns=["A","B","C"])

print(arr2)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

### Exploring Pandas

In [12]:
import pandas as pd

In [13]:
data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Arun",
             "Kiran", "Neha", "Ravi", "Anu", "Vijay"],

    "Age": [21, 22, 23, 21, 24, 22, 25, 23, 21, 24],

    "City": ["Bengaluru", "Mumbai", "Delhi", "Chennai", "Bengaluru",
             "Hyderabad", "Mumbai", "Delhi", "Chennai", "Bengaluru"],

    "Salary": [25000, 30000, 28000, 35000, None,
               32000, 40000, 29000, 27000, 35000]
}

df=pd.DataFrame(data)
df

    Name  Age       City   Salary
0  Rahul   21  Bengaluru  25000.0
1  Priya   22     Mumbai  30000.0
2   Amit   23      Delhi  28000.0
3  Sneha   21    Chennai  35000.0
4   Arun   24  Bengaluru      NaN
5  Kiran   22  Hyderabad  32000.0
6   Neha   25     Mumbai  40000.0
7   Ravi   23      Delhi  29000.0
8    Anu   21    Chennai  27000.0
9  Vijay   24  Bengaluru  35000.0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes

In [15]:
df.describe()

             Age        Salary
count  10.000000      9.000000
mean   22.600000  31222.222222
std     1.429841   4737.556801
min    21.000000  25000.000000
25%    21.250000  28000.000000
50%    22.500000  30000.000000
75%    23.750000  35000.000000
max    25.000000  40000.000000

In [19]:
df[['Name','City']]

    Name       City
0  Rahul  Bengaluru
1  Priya     Mumbai
2   Amit      Delhi
3  Sneha    Chennai
4   Arun  Bengaluru
5  Kiran  Hyderabad
6   Neha     Mumbai
7   Ravi      Delhi
8    Anu    Chennai
9  Vijay  Bengaluru

In [21]:
df.drop('City',axis=1)

    Name  Age   Salary
0  Rahul   21  25000.0
1  Priya   22  30000.0
2   Amit   23  28000.0
3  Sneha   21  35000.0
4   Arun   24      NaN
5  Kiran   22  32000.0
6   Neha   25  40000.0
7   Ravi   23  29000.0
8    Anu   21  27000.0
9  Vijay   24  35000.0

In [22]:
df

    Name  Age       City   Salary
0  Rahul   21  Bengaluru  25000.0
1  Priya   22     Mumbai  30000.0
2   Amit   23      Delhi  28000.0
3  Sneha   21    Chennai  35000.0
4   Arun   24  Bengaluru      NaN
5  Kiran   22  Hyderabad  32000.0
6   Neha   25     Mumbai  40000.0
7   Ravi   23      Delhi  29000.0
8    Anu   21    Chennai  27000.0
9  Vijay   24  Bengaluru  35000.0

In [23]:
df["Salary"].fillna(df["Salary"].mean(),inplace=True)

In [24]:
df

    Name  Age       City        Salary
0  Rahul   21  Bengaluru  25000.000000
1  Priya   22     Mumbai  30000.000000
2   Amit   23      Delhi  28000.000000
3  Sneha   21    Chennai  35000.000000
4   Arun   24  Bengaluru  31222.222222
5  Kiran   22  Hyderabad  32000.000000
6   Neha   25     Mumbai  40000.000000
7   Ravi   23      Delhi  29000.000000
8    Anu   21    Chennai  27000.000000
9  Vijay   24  Bengaluru  35000.000000

In [25]:
df.drop_duplicates(inplace=True)

In [26]:
df

    Name  Age       City        Salary
0  Rahul   21  Bengaluru  25000.000000
1  Priya   22     Mumbai  30000.000000
2   Amit   23      Delhi  28000.000000
3  Sneha   21    Chennai  35000.000000
4   Arun   24  Bengaluru  31222.222222
5  Kiran   22  Hyderabad  32000.000000
6   Neha   25     Mumbai  40000.000000
7   Ravi   23      Delhi  29000.000000
8    Anu   21    Chennai  27000.000000
9  Vijay   24  Bengaluru  35000.000000